app:
  env: none

server:
  port: 8443
spring:
  profiles:
    active: local,prod
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hiberate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    platform: mysql
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/eventpro?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username:
    password:

security:
  jwt:
    #    expire-milliseconds: 3600000 # an hour
    expire-milliseconds: 31622400 # a year

aws:
  region: us-west-2
  access-key: <access key>
  secret-key: <access secret>
  s3-bucket: <bucket name>
  s3-url: https://${aws.s3-bucket}.s3-${aws.region}.amazonaws.com
  s3-accelerate-url: https://${aws.s3-bucket}.s3-accelerate.amazonaws.com
  cloud-front-url: <Cloud Front base URL>
